version: '3.8'
services:
  db:
    build: ./db
    container_name: sem_db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_HOST=%
    ports:
      - "33060:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: sem_app
    depends_on:
      db:
        condition: service_healthy
